### ISSUE TITLE
Test builds

### ISSUE THREAD

**Issue by lextm** [lextm/monodevelop-windows#1]
I started to ship test build of MSI installer. Please try out and leave your feedback below.

**Comment by lextm** [comment]
https://ci.appveyor.com/project/lextm/monodevelop-windows/build/artifacts

Initial build for MonoDevelop 7.8 on Windows. Only tested .NET Framework console application compilation and debugging.

**Comment by Alex527** [comment]
Amazing news!
![Screenshot_4](https://user-images.githubusercontent.com/11727103/57973413-47115000-79b1-11e9-8ffb-bc7a25007901.png)
But I got this error after install. Not sure where I can find any logs though.
GTK# is also installed, 2.12.45.

**Comment by lextm** [comment]
@Alex527 can you describe a little bit more about your environment? Windows 7?

**Comment by lextm** [comment]
A few improvements today,

* Git/SVN addins are enabled.
* Removed PCL project template and revised other C# project templates.
* Fixed .NET Core project support.

**Comment by lextm** [comment]
Progress today,

* Fixed language bindings addins.
* Fixed a few templates.

**Comment by Alex527** [comment]
I run Windows 10 Home, version 1809, OS build 17763.503 with latest updates.
Btw, I installed latest builds and I don't have that crash on startup anymore. .Net Core projects creation is fine, but having some error message after creation of gtk# project.
![Screenshot_7](https://user-images.githubusercontent.com/11727103/58043190-37c30b80-7b45-11e9-836e-4d2416d24b9a.png)

**Comment by lextm** [comment]
You might try the steps to see what else we can dig out,

1. Open a MonoDevelop instance (like `C:\Program Files (x86)\MonoDevelop\bin\MonoDevelop.exe`).
1. Instead of creating/opening a project, click `Run | Debug Application...` menu item.
1. Set Command to `C:\Program Files (x86)\MonoDevelop\bin\MonoDevelop.exe`.
1. Set Working Directory to `C:\Program Files (x86)\MonoDevelop\bin`.
1. Click OK.
1. Wait till the second instance of MonoDevelop launches, switch back to the first instance and click `View | Pads | Application Output - MonoDevelop.exe` to reveal the tracing.
1. Switch back to the second instance, and reproduce the issue.

Now the tracing should show what errors happened. From that we can see how the installer can be improved.

**Comment by lextm** [comment]
Progress today,

* Switched to release build.
* Removed invalid assembly redirection.

**Comment by lextm** [comment]
Progress today,
* VS2019 is blocked. Forced to use VS2017/MSBuild 15 to eliminate incompatibilities.
* Added missing files.

Latest build is https://ci.appveyor.com/project/lextm/monodevelop-windows/builds/24741528

**Comment by mickeyjf** [comment]
Tried the msi this morning on Windows 10 Professional. Only basic install issues I ran into were my own - needing to install VS2019 to get the MSbuild files. So far, so good. MD runs, builds my solution with no errors reported.  

Some puzzling behavior tho'. My source files are NOT read only - I can edit them with another text editor, but not in MonoDevelop. ?? Also, although my project builds with no errors, every type definition has a sqiggly red line under it  and "Predefined System.Object is not defined or imported" and for all my types "the type or namespace 'blah' could not be found" or "..does not exist in the current context."

Is there some obvious default setting or required dlls that I've missed?

**Comment by lextm** [comment]
@mickeyjf You should try to download and install again. https://ci.appveyor.com/project/lextm/monodevelop-windows/builds/24739589

It was my mistake to enable support of VS2019 and MSBuild 16. You might get some success with VS2019, but there are certain bugs no one can fix.

VS2019 support is expected, once MonoDevelop 8.1 branch is stable enough for me to build it and create a corresponding installer.

**Comment by mickeyjf** [comment]
Uninstalled VS 2019, Installed VS2017 (Community). No change in behavior of MD. Your email of 2019-05-16 said to copy the dlls from ...BuildTools\MSBuild\15.0\Bin, but that path does not exist for VS2017 Community. I copied all the dlls from ...2017\MSBuild\15.0\Bin to the directory with MonoDevelop.exe, but still not able to edit files, and when I try to build I get error MSB3491 (path too long) trying to write to FileListAbsolute.txt way down the tree from c:\Program Files (x86). I'll try moving everything to a shorter path and see if that helps.

**Comment by lextm** [comment]
@mickeyjf The file editing issue was caused by missing files. A new build is available,

 https://ci.appveyor.com/project/lextm/monodevelop-windows/builds/24741528

I am not quite about the path too long issue, but what kind of project are you working on?

**Comment by mickeyjf** [comment]
Got the latest. Can now edit and build again. Still seeing "Predefined System.Object is not defined or imported" etc, but path error has gone away. Debugger appears to be ignoring my breakpoints, but that may be something I've missed. Have to go, I will look at this further tomorrow.

**Comment by mickeyjf** [comment]
I lied. Path error still there, although referring to a different file this time. May be one of those bogus error messages that really refers to something else? But the name of the file it referes to is inconsistent and changes with each Clean or Build attempt, and one time it did not appear and I was able to build and run in the debugger. This is a desktop console app that talks to a Postgres DB.

Error message:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5,5): Error MSB3491: Could not write lines to file "..\..\..\Program Files (x86)\MonoDevelop\bin\Debug\V5Base.csproj.CoreCompileInputs.cache". Access to the path 'C:\Program Files (x86)\MonoDevelop\bin\Debug\V5Base.csproj.CoreCompileInputs.cache' is denied. (MSB3491) (V5Base)

**Comment by mickeyjf** [comment]
I tried re-installing MD in a directory higher up than C:\Program Files, but it apparently was not able to find GTK unless in the default location, and insisted that I needed to install it.

**Comment by lextm** [comment]
@mickeyjf Can you open up the project file and review settings like intermediate path?

I don't know (yet) why MonoDevelop 7.x tries to modify that and point to "......\Program Files (x86)\MonoDevelop\bin\", but once you delete such broken settings, you should be able to compile successfully.

**Comment by mickeyjf** [comment]
I confess that I don't understand everything that goes on in the .proj file for building, but I changed to an absolute path (replaced ..\..\..\ with c:\) and still get the same error. :

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5,5): Error MSB3491: Could not write lines to file "C:\Program Files (x86)\MonoDevelop\bin\Debug\EngineV5.csproj.FileListAbsolute.txt". Access to the path 'C:\Program Files (x86)\MonoDevelop\bin\Debug\EngineV5.csproj.FileListAbsolute.txt' is denied. (MSB3491) (EngineV5)

Since the path is only ~ 80 chars rather than the limit of 260 indicated in the error message, I'm suspicious that the message is not reporting the true issue.

The ..\..\..\ apparently treated '\' as an escape when I copy-pasted it here and showed as ....\.

On my Win7 machine (with the sightly older, working, MD) the .proj files  have no BaseIntermediateProjectPath. On the new Win10 PC I just removed that line entirely from the several .proj files that had it (3 out of 4) and now I am (so far) able to clean, build and run apparently normally. Any education you care to give me about that line I removed (or anything else!) is appreciated. Thanks!

**Comment by lextm** [comment]
Thanks for the confirmation.

The miserable "BaseIntermediateProjectPath" issue is part of MonoDevelop 7.x, which you did nothing wrong. I had no idea where it came so could not fix it yet.

Luckily once removed it won't come back, and typical .NET project files should not have an explicit entry of "BaseIntermediateProjectPath".

**Comment by mickeyjf** [comment]
Interesting that it's in there although things run fine (better, even) without it. Sorry to have taken so much of your time tracking this down, but we've probably both learned something.

**Comment by lextm** [comment]
Signed the latest installer, so we have an initial release https://github.com/lextm/monodevelop-windows/releases
