### ISSUE TITLE
Feature Request: Use of Mono build tools?

### ISSUE THREAD

**Issue by GitHubinat0r** [lextm/monodevelop-windows#8]
This may be outside of the scope of the project, but I'd like to request consideration for the ability to use mono to do builds (like in Linux) instead of relying on MS-Build-Tools .

**Comment by lextm** [comment]
This repo only builds MonoDevelop on Windows, so no plan to use Mono's build chain.

**Comment by GitHubinat0r** [comment]
Forgive my ignorance but isn’t Mono cross platform or am I misunderstanding something?


https://www.mono-project.com/docs/getting-started/install/windows/

**Comment by lextm** [comment]
This is a personal repo. If you look for the Mono project, please go to https://github.com/mono/monodevelop

**Comment by GitHubinat0r** [comment]
Do you have any documentation as to how you’re successfully making this build? Do you have a specific version you’re targeting?

It will probably be more expedient for me to remove the MS Build Tools hard dependency and look into how to use Mono (IE how builds can occur on Mac, Linux, and yes, Windows) than try to discuss further here.

**Comment by lextm** [comment]
What kind of documentation are you looking for? All my changes are subtle (compared to the original MonoDevelop code base), and you can review the commits to learn what they are and easily figure out why.

Your thought of "remove the MS Build Tools" is also interesting. Mono is owned by Microsoft now, and its code base uses many Microsoft bits (for good). So if your goal is otherwise, it won't work out.

**Comment by GitHubinat0r** [comment]
I’m fine with Microsoft. The goal is to avoid their licensing restrictions tied to Visual Studio Build Tools when Mono works just as well in most use cases.

**Comment by lextm** [comment]
Then that does not fall into the scope of this repo. You can create your own fork and play with the code.

**Comment by GitHubinat0r** [comment]
That’s fine. I’ll take a look at it. One last question. Was the Visual Studio requirement hardcoded by you or was that already in the original source?

**Comment by lextm** [comment]
I set a VS 2017 requirement in this place, https://github.com/lextm/monodevelop/commit/b166ae725045fe6d5dece3c6e13b4250feabba1f
