### ISSUE TITLE
Can't create projects.

### ISSUE THREAD

**Issue by CarterSnich** [lextm/monodevelop-windows#9]
![image](https://user-images.githubusercontent.com/52433531/80742335-c9a50800-8b4d-11ea-9411-97a8e74d5e5f.png)

`The type initializer for 'MonoDevelop.Projects.MSBuild.MSBuildEvaluationContext' threw an exception.`

After installing and starts a new project, that shows up after I click 'Create'. I have MSBuild 16 installed, is it incompatible? Please, help me with this. I don't really know what I am doing. Thank you. Just wanna start C# with a light-weight IDE.

**Comment by lextm** [comment]
Clearly only MSBuild 15 is supported by this repo, https://github.com/lextm/monodevelop-windows/blob/master/README.md
